name = "mbtitest"
compatibility_date = "2024-12-08"
pages_build_output_dir = "./public"

[[r2_buckets]]
binding = "MBTI_BUCKET" # 또는 ASSETS
bucket_name = "mbti-assets"

[vars]
ASSETS_BASE = "https://pub-9394623df95a4f669f145a4ede63d588.r2.dev"
R2_PUBLIC_BASE_URL = "https://pub-9394623df95a4f669f145a4ede63d588.r2.dev"