name = "mbtitest"
compatibility_date = "2024-12-08"

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "DB"
id = "5a0e18d5651c42ffa582f57ee1e18c9b"
preview_id = "5a0e18d5651c42ffa582f57ee1e18c9b"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "mbti-assets"

[vars]
ASSETS_BASE = "https://01d6807196c93a4774c1bb50ee8f4ebb.r2.cloudflarestorage.com/mbti-assets"
ADMIN_TOKEN = "change-me" # HMAC/Service Token/Access 사용 권장